export const copy = {
  bn: {
    brand: "হাঁড়ি ভাঙা", strap: "কারণ কাউকে তো মেস সামলাতেই হবে", badge: "মেসের হিসাব, এবার ডিজিটাল", hero: "মেসের হিসাব, meal off, boarder, guest — সব এক হাঁড়িতে। নোটবুকের কলাম আর হাতে আঁকতে হবে না।", start: "শুরু করো", nightmare: "ম্যানেজারের রাত ১১:৫৮টার দুঃস্বপ্ন", familiar: "প্রতিটা মেসেই এই গল্প চেনা।", storyEnd: "আর ম্যানেজার? খাতা খোলে... ভুলে যায় কে কী খেয়েছে।", digital: "তোমার মেসটাও ডিজিটাল করে ফেলো",
    create: "নতুন মেস", join: "মেসে জয়েন করো", signIn: "Google দিয়ে সাইন ইন", signed: "সাইন ইন করা আছে", logout: "বেরিয়ে যাও", continue: "এগিয়ে যাও", loading: "লোড হচ্ছে…", error: "কিছু একটা সমস্যা হয়েছে। আবার চেষ্টা করো।", noConfig: "Firebase সেটআপ বাকি", noConfigDetail: ".env ফাইলে Firebase credentials যোগ করে আবার চালাও।",
    createTitle: "তোমার মেসের নাম কী?", messName: "মেসের নাম", members: "সদস্য", memberHint: "সবাইকে পরে এডিট করা যাবে।", add: "আরও একজন", namePlaceholder: "যেমন: নেতাজি মেস", personPlaceholder: "সদস্যের নাম", joinTitle: "মেসে যোগ দাও", joinHint: "ম্যানেজারের দেওয়া কোডটি লেখো।", joinNow: "জয়েন করো", joinCode: "মেস কোড", invalidCode: "এই কোডে কোনো মেস পাওয়া যায়নি।", alreadyMember: "তুমি ইতিমধ্যে এই মেসে আছো।",
    monthSetup: "কে boarder, কে guest?", min: "ন্যূনতম Boarder Meal", mealsMonth: "মিল / মাস", tracker: "মিল ট্র্যাকার খোলো", boarder: "Boarder", guest: "Guest", morning: "সকাল", night: "রাত", total: "মোট", summary: "মাসের সারাংশ", reached: "ন্যূনতম পূর্ণ", remaining: "আরও {n} মিল দরকার", manager: "ম্যানেজার", code: "কোড", editLocked: "শুধু এই মাসের ম্যানেজার পরিবর্তন করতে পারবেন",
    meals: "Meal Tracker", guestMeals: "Guest Meals", settings: "Mess Settings", bazar: "Bazar", reports: "Summary", calculations: "Calculations", addMember: "সদস্য যোগ করো", edit: "এডিট", remove: "বাদ দাও", save: "সেভ করো", cancel: "বাতিল", back: "পেছনে", close: "বন্ধ করো", activeMembers: "সক্রিয় সদস্য", guestName: "অতিথির নাম", quantity: "পরিমাণ", mealType: "খাবারের ধরন", addGuestMeal: "Guest Meal যোগ করো", date: "তারিখ", addExpense: "খরচ যোগ করো", item: "কী কিনলে?", amount: "টাকার পরিমাণ", category: "ক্যাটাগরি", recentExpenses: "সাম্প্রতিক খরচ", totalExpense: "মোট খরচ", copy: "কপি", copied: "কপি হয়েছে", regenerate: "নতুন কোড", confirmRegenerate: "নিশ্চিত? পুরনো কোড আর কাজ করবে না।", managerOnly: "এটি শুধু ম্যানেজারের জন্য", removeWarning: "সদস্যটি তালিকা থেকে বাদ যাবে, কিন্তু পুরনো meal history থাকবে।", confirm: "নিশ্চিত করো", month: "চলতি মাস", expensePlaceholder: "হিসাব শিগগিরই আসছে", noGuests: "এখনও কোনো guest meal নেই", noExpenses: "এখনও কোনো খরচ নেই", fish: "Fish", meat: "Meat", egg: "Egg", veg: "Veg", other: "Other"
  },
  en: {
    brand: "Hari Bhanga", strap: "Because someone has to run the mess", badge: "Mess life, now digital", hero: "Meal offs, boarders and guests — everything in one pot. No more ruling notebook columns by hand.", start: "Get started", nightmare: "The manager's 11:58 PM nightmare", familiar: "Every mess knows this story.", storyEnd: "And the manager? Opens the notebook… and forgets who ate what.", digital: "Make your mess digital",
    create: "Create a mess", join: "Join a mess", signIn: "Continue with Google", signed: "Signed in", logout: "Log out", continue: "Continue", loading: "Loading…", error: "Something went wrong. Please try again.", noConfig: "Firebase setup needed", noConfigDetail: "Add Firebase credentials to .env, then restart the app.",
    createTitle: "What is your mess called?", messName: "Mess name", members: "Members", memberHint: "You can edit this list later.", add: "Add another", namePlaceholder: "e.g. Netaji Mess", personPlaceholder: "Member name", joinTitle: "Join a mess", joinHint: "Enter the code shared by your manager.", joinNow: "Join mess", joinCode: "Mess code", invalidCode: "No mess was found with that code.", alreadyMember: "You already belong to this mess.",
    monthSetup: "Who is a boarder or guest?", min: "Minimum boarder meals", mealsMonth: "meals / month", tracker: "Open meal tracker", boarder: "Boarder", guest: "Guest", morning: "Morning", night: "Night", total: "Total", summary: "Monthly summary", reached: "Minimum reached", remaining: "{n} more meals needed", manager: "Manager", code: "Code", editLocked: "Only this month's manager can make changes",
    meals: "Meal Tracker", guestMeals: "Guest Meals", settings: "Mess Settings", bazar: "Bazar", reports: "Summary", calculations: "Calculations", addMember: "Add member", edit: "Edit", remove: "Remove", save: "Save", cancel: "Cancel", back: "Back", close: "Close", activeMembers: "Active members", guestName: "Guest name", quantity: "Quantity", mealType: "Meal type", addGuestMeal: "Add guest meal", date: "Date", addExpense: "Add expense", item: "What did you buy?", amount: "Amount", category: "Category", recentExpenses: "Recent expenses", totalExpense: "Total expenses", copy: "Copy", copied: "Copied", regenerate: "New code", confirmRegenerate: "Are you sure? The old code will stop working.", managerOnly: "This is for the manager only", removeWarning: "The member will leave the active list; their past meal history stays intact.", confirm: "Confirm", month: "Current month", expensePlaceholder: "Calculations are coming soon", noGuests: "No guest meals yet", noExpenses: "No expenses yet", fish: "Fish", meat: "Meat", egg: "Egg", veg: "Veg", other: "Other"
  }
};
export function useT(lang) { return (key, vars = {}) => (copy[lang][key] || key).replace(/\{(\w+)\}/g, (_, k) => vars[k] ?? ""); }
